# Generated by cucumber-sinatra. (2012-02-05 18:16:20 -0600)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/main.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Sinatra::Application
Capybara.javascript_driver = :webkit

class Sinatra::ApplicationWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  Sinatra::ApplicationWorld.new
end
